[2022-12-06 11:18:20,084] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-06T11:17:48.712978+00:00 [queued]>
[2022-12-06 11:18:20,119] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-06T11:17:48.712978+00:00 [queued]>
[2022-12-06 11:18:20,119] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:18:20,119] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-12-06 11:18:20,119] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-12-06 11:18:20,127] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): LoadPositionsInMongoDB> on 2022-12-06T11:17:48.712978+00:00
[2022-12-06 11:18:20,131] {standard_task_runner.py:52} INFO - Started process 294 to run task
[2022-12-06 11:18:20,135] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_mongo_db_dag', 'LoadPositionsInMongoDB', '2022-12-06T11:17:48.712978+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_mongo_db_dag.py', '--cfg-path', '/tmp/tmp56lz3j9t', '--error-file', '/tmp/tmp4z73lcng']
[2022-12-06 11:18:20,136] {standard_task_runner.py:77} INFO - Job 13: Subtask LoadPositionsInMongoDB
[2022-12-06 11:18:20,177] {logging_mixin.py:104} INFO - Running <TaskInstance: my_mongo_db_dag.LoadPositionsInMongoDB 2022-12-06T11:17:48.712978+00:00 [running]> on host 90b7908d868d
[2022-12-06 11:18:20,226] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_mongo_db_dag
AIRFLOW_CTX_TASK_ID=LoadPositionsInMongoDB
AIRFLOW_CTX_EXECUTION_DATE=2022-12-06T11:17:48.712978+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-06T11:17:48.712978+00:00
[2022-12-06 11:18:20,408] {logging_mixin.py:104} INFO - debut de chargement des donn√©es dans mongodb
[2022-12-06 11:18:20,408] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_mongo_db_dag.py", line 55, in load
    l.load(cl, dict_positions)
  File "/opt/airflow/scripts/mongo/load_aircraft_position_data_in_mongodb.py", line 28, in load
    mycol.insert_many(dict_positions)
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 690, in insert_many
    blk.ops = [doc for doc in gen()]
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 690, in <listcomp>
    blk.ops = [doc for doc in gen()]
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/collection.py", line 681, in gen
    common.validate_is_document_type("document", document)
  File "/home/airflow/.local/lib/python3.6/site-packages/pymongo/common.py", line 516, in validate_is_document_type
    "collections.MutableMapping" % (option,)
TypeError: document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
[2022-12-06 11:18:20,410] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=my_mongo_db_dag, task_id=LoadPositionsInMongoDB, execution_date=20221206T111748, start_date=20221206T111820, end_date=20221206T111820
[2022-12-06 11:18:20,467] {local_task_job.py:151} INFO - Task exited with return code 1
